openapi: 3.0.0
info:
  title: API Loja Virtual
  version: 0.1
tags:
  - name: produtos
paths:
  /produtos:
    get:
      tags:
        - produtos
      summary: Retorna todos os produtos
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
  /users/login:
    post:
      tags:
        - users
      summary: Login de usuário
      requestBody:
        description: Email e senha do usuário
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  auth:
                    type: boolean
                  token:
                    type: string
components:
  schemas:
    Produto:
      type: object
      properties:
        nome:
          type: string
        preco:
          type: number
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
